require('dotenv').config();
export const API_TITLE = process.env.TITLE;
export const API_PORT = parseInt(process.env.CLEO_PORT);
export const MONGO_DB_URL = process.env.MONGO_DB_URL;
export const SESSION_SECRET = process.env.SESSION_SECRET;
export const PASSWORD_SALT = process.env.PASSWORD_SALT;
export const HTTP_STATUS_OK = 200;
export const HTTP_STATUS_CREATED = 201;
export const HTTP_STATUS_BAD_REQUEST = 400;
export const HTTP_STATUS_UNAUTHORIZED = 401;
export const HTTP_STATUS_NOT_FOUND = 404;
export const HTTP_STATUS_CONFLICT = 409;
export const HTTP_STATUS_INTERNAL_SERVER_ERROR = 500;